import BisBall from './balls/bisball.png'
import BisBallSleep from './balls/bisballsleep.png'
import MegaBall from './balls/megaball.png'
import MegaBallSleep from './balls/megaballsleep.png'
import PokeBall from './balls/pokeball.png'
import PokeBallSleep from './balls/pokeballsleep.png'
import UltraBall from './balls/ultraball.png'
import UltraBallSleep from './balls/ultraballsleep.png'
import VeloxBall from './balls/veloxball.png'
import VeloxBallSleep from './balls/veloxballsleep.png'
import BerryIcon from './berry.png'
import Bulbasaur from './bulbasaur.png'
import Charmander from './charmander.png'
import CosmeticsIcon from './cosmetics.png'
import { default as Dratini, default as Eevee } from './dratini.png'
import EggMovesIcon from './egg-moves.png'
import EggIcon from './egg.png'
import ItemsIcon from './items.png'
import Lunatone from './lunatone.png'
import Meowth from './meowth.png'
import MarketIcon from './investments.png'
import HeartIcon from './heart.png'
import MultiIcon from './multi.png'
import TradeAdIcon from './tradead.png'
import Pikachu from './pikachu.png'
import PokedexIcon from './pokedex.png'
import RealEggIcon from './realEgg.png'
import ShinyIcon from './shiny.png'
import Snorlax from './snorlax.png'
import Solrock from './solrock.png'
import ArchetypeIcon from './archetype.png'
import BreedingIcon from './breeding.png'
import AllItemsIcon from './allitems.png'


export {
    HeartIcon, AllItemsIcon, BreedingIcon, EggIcon, Solrock, Lunatone, ShinyIcon, PokeBall, PokeBallSleep, MegaBall, MegaBallSleep, UltraBall, UltraBallSleep, BisBall, BisBallSleep, PokedexIcon, VeloxBall, VeloxBallSleep, RealEggIcon, EggMovesIcon, CosmeticsIcon, Meowth, Pikachu, Snorlax, Bulbasaur, Charmander, Dratini, Eevee, BerryIcon, MarketIcon, MultiIcon, ItemsIcon, TradeAdIcon, ArchetypeIcon
}
